[package]
name = "egg_game_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
tiny-skia = "0.11.1"
egg_core = { path = "egg_core" }

[workspace]

members = [
    "egg_core",
]